// Real tracks, served from public/audio/ (derivatives generated by
// scripts/process-assets.sh from the masters in assets/playlist/).
// Reorder freely; the player follows this order.
export type Track = {
  id: string;
  title: string;
  src: string;
  /** Display duration, shown before metadata loads. */
  durationLabel: string;
};

export const tracks: Track[] = [
  {
    id: "shootingspree",
    title: "Shooting Simulator (game soundtrack)",
    src: "/audio/shootingspree.m4a",
    durationLabel: "1:57",
  },
  {
    id: "please-do-not-lean",
    title: "Please Do Not Lean",
    src: "/audio/please-do-not-lean.m4a",
    durationLabel: "1:20",
  },
  {
    id: "battle-against-a-cute-child",
    title: "Battle Against a Cute Child",
    src: "/audio/battle-against-a-cute-child.m4a",
    durationLabel: "1:24",
  },
  {
    id: "roland-and-marianne",
    title: "Roland and Marianne in the Ballroom (collab with a friend)",
    src: "/audio/roland-and-marianne.m4a",
    durationLabel: "2:52",
  },
  {
    id: "nothing-farm",
    title: "Nothing Farm",
    src: "/audio/nothing-farm.m4a",
    durationLabel: "1:22",
  },
  {
    id: "zar",
    title: "Zar (game soundtrack)",
    src: "/audio/zar.m4a",
    durationLabel: "2:14",
  },
  {
    id: "i-3d-printed-this-horn",
    title: "I 3D Printed This Horn",
    src: "/audio/i-3d-printed-this-horn.mp3",
    durationLabel: "1:18",
  },
  {
    id: "constellations",
    title: "Constellations (ambient)",
    src: "/audio/constellations.m4a",
    durationLabel: "7:12",
  },
  {
    id: "beatbattle",
    title: "Beat Battle (all sounds made from a default piano)",
    src: "/audio/beatbattle.m4a",
    durationLabel: "1:51",
  },
  {
    id: "crazybass",
    title: "Crazy Bass",
    src: "/audio/crazybass.m4a",
    durationLabel: "1:09",
  },
  {
    id: "playing-with-the-buchla",
    title: "Playing With the Buchla",
    src: "/audio/playing-with-the-buchla.m4a",
    durationLabel: "1:16",
  },
  {
    id: "underscore",
    title: "Underscore",
    src: "/audio/underscore.m4a",
    durationLabel: "1:14",
  },
];
